/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DropdownOption = IDL.Record({
  'displayName' : IDL.Text,
  'value' : IDL.Text,
  'parent' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FormField = IDL.Record({
  'order' : IDL.Nat,
  'displayLabel' : IDL.Text,
  'required' : IDL.Bool,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  'fieldName' : IDL.Text,
  'fieldType' : IDL.Variant({
    'Date' : IDL.Null,
    'Textarea' : IDL.Null,
    'Text' : IDL.Null,
    'Checkbox' : IDL.Null,
    'Number' : IDL.Null,
    'Dropdown' : IDL.Null,
  }),
});
export const FormDefinition = IDL.Record({
  'formName' : IDL.Text,
  'fields' : IDL.Vec(FormField),
});
export const ReportDefinition = IDL.Record({
  'filters' : IDL.Vec(
    IDL.Record({
      'filterType' : IDL.Variant({
        'Date' : IDL.Null,
        'Text' : IDL.Null,
        'Number' : IDL.Null,
      }),
      'fieldName' : IDL.Text,
    })
  ),
  'metrics' : IDL.Vec(
    IDL.Record({
      'metricType' : IDL.Variant({
        'Sum' : IDL.Null,
        'Average' : IDL.Null,
        'Count' : IDL.Null,
      }),
      'fieldName' : IDL.Text,
    })
  ),
  'reportName' : IDL.Text,
  'groupBy' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const EntityRecord = IDL.Record({
  'id' : IDL.Text,
  'data' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'createdAt' : Time,
  'formName' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
});
export const ImportStatus = IDL.Record({
  'errors' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
  'totalRows' : IDL.Nat,
  'timestamp' : Time,
  'successfulRows' : IDL.Nat,
  'failedRows' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDropdownOption' : IDL.Func([IDL.Text, DropdownOption], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntity' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
  'createForm' : IDL.Func([FormDefinition], [], []),
  'createReport' : IDL.Func([ReportDefinition], [], []),
  'getAllForms' : IDL.Func([], [IDL.Vec(FormDefinition)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(ReportDefinition)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDropdownOptions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DropdownOption)],
      ['query'],
    ),
  'getEntities' : IDL.Func([IDL.Text], [IDL.Vec(EntityRecord)], ['query']),
  'getEntity' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(EntityRecord)],
      ['query'],
    ),
  'getForm' : IDL.Func([IDL.Text], [IDL.Opt(FormDefinition)], ['query']),
  'getImportStatus' : IDL.Func([IDL.Text], [IDL.Opt(ImportStatus)], ['query']),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(ReportDefinition)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateImportStatus' : IDL.Func([IDL.Text, ImportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DropdownOption = IDL.Record({
    'displayName' : IDL.Text,
    'value' : IDL.Text,
    'parent' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FormField = IDL.Record({
    'order' : IDL.Nat,
    'displayLabel' : IDL.Text,
    'required' : IDL.Bool,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
    'fieldName' : IDL.Text,
    'fieldType' : IDL.Variant({
      'Date' : IDL.Null,
      'Textarea' : IDL.Null,
      'Text' : IDL.Null,
      'Checkbox' : IDL.Null,
      'Number' : IDL.Null,
      'Dropdown' : IDL.Null,
    }),
  });
  const FormDefinition = IDL.Record({
    'formName' : IDL.Text,
    'fields' : IDL.Vec(FormField),
  });
  const ReportDefinition = IDL.Record({
    'filters' : IDL.Vec(
      IDL.Record({
        'filterType' : IDL.Variant({
          'Date' : IDL.Null,
          'Text' : IDL.Null,
          'Number' : IDL.Null,
        }),
        'fieldName' : IDL.Text,
      })
    ),
    'metrics' : IDL.Vec(
      IDL.Record({
        'metricType' : IDL.Variant({
          'Sum' : IDL.Null,
          'Average' : IDL.Null,
          'Count' : IDL.Null,
        }),
        'fieldName' : IDL.Text,
      })
    ),
    'reportName' : IDL.Text,
    'groupBy' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const EntityRecord = IDL.Record({
    'id' : IDL.Text,
    'data' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'createdAt' : Time,
    'formName' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
  });
  const ImportStatus = IDL.Record({
    'errors' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
    'totalRows' : IDL.Nat,
    'timestamp' : Time,
    'successfulRows' : IDL.Nat,
    'failedRows' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDropdownOption' : IDL.Func([IDL.Text, DropdownOption], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntity' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
    'createForm' : IDL.Func([FormDefinition], [], []),
    'createReport' : IDL.Func([ReportDefinition], [], []),
    'getAllForms' : IDL.Func([], [IDL.Vec(FormDefinition)], ['query']),
    'getAllReports' : IDL.Func([], [IDL.Vec(ReportDefinition)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDropdownOptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DropdownOption)],
        ['query'],
      ),
    'getEntities' : IDL.Func([IDL.Text], [IDL.Vec(EntityRecord)], ['query']),
    'getEntity' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(EntityRecord)],
        ['query'],
      ),
    'getForm' : IDL.Func([IDL.Text], [IDL.Opt(FormDefinition)], ['query']),
    'getImportStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImportStatus)],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(ReportDefinition)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateImportStatus' : IDL.Func([IDL.Text, ImportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };