/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DropdownOption {
  'displayName' : string,
  'value' : string,
  'parent' : [] | [string],
}
export interface EntityRecord {
  'id' : string,
  'data' : Array<[string, string]>,
  'createdAt' : Time,
  'formName' : string,
  'updatedAt' : [] | [Time],
}
export interface FormDefinition {
  'formName' : string,
  'fields' : Array<FormField>,
}
export interface FormField {
  'order' : bigint,
  'displayLabel' : string,
  'required' : boolean,
  'options' : [] | [Array<string>],
  'fieldName' : string,
  'fieldType' : { 'Date' : null } |
    { 'Textarea' : null } |
    { 'Text' : null } |
    { 'Checkbox' : null } |
    { 'Number' : null } |
    { 'Dropdown' : null },
}
export interface ImportStatus {
  'errors' : Array<{ 'row' : bigint, 'message' : string }>,
  'totalRows' : bigint,
  'timestamp' : Time,
  'successfulRows' : bigint,
  'failedRows' : bigint,
}
export interface ReportDefinition {
  'filters' : Array<
    {
      'filterType' : { 'Date' : null } |
        { 'Text' : null } |
        { 'Number' : null },
      'fieldName' : string,
    }
  >,
  'metrics' : Array<
    {
      'metricType' : { 'Sum' : null } |
        { 'Average' : null } |
        { 'Count' : null },
      'fieldName' : string,
    }
  >,
  'reportName' : string,
  'groupBy' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDropdownOption' : ActorMethod<[string, DropdownOption], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntity' : ActorMethod<[string, Array<[string, string]>], string>,
  'createForm' : ActorMethod<[FormDefinition], undefined>,
  'createReport' : ActorMethod<[ReportDefinition], undefined>,
  'getAllForms' : ActorMethod<[], Array<FormDefinition>>,
  'getAllReports' : ActorMethod<[], Array<ReportDefinition>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDropdownOptions' : ActorMethod<[string], Array<DropdownOption>>,
  'getEntities' : ActorMethod<[string], Array<EntityRecord>>,
  'getEntity' : ActorMethod<[string, string], [] | [EntityRecord]>,
  'getForm' : ActorMethod<[string], [] | [FormDefinition]>,
  'getImportStatus' : ActorMethod<[string], [] | [ImportStatus]>,
  'getReport' : ActorMethod<[string], [] | [ReportDefinition]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateImportStatus' : ActorMethod<[string, ImportStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];