/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EntityRecord {
    id: string;
    data: Array<[string, string]>;
    createdAt: Time;
    formName: string;
    updatedAt?: Time;
}
export type Time = bigint;
export interface DropdownOption {
    displayName: string;
    value: string;
    parent?: string;
}
export interface FormField {
    order: bigint;
    displayLabel: string;
    required: boolean;
    options?: Array<string>;
    fieldName: string;
    fieldType: Variant_Date_Textarea_Text_Checkbox_Number_Dropdown;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ReportDefinition {
    filters: Array<{
        filterType: Variant_Date_Text_Number;
        fieldName: string;
    }>;
    metrics: Array<{
        metricType: Variant_Sum_Average_Count;
        fieldName: string;
    }>;
    reportName: string;
    groupBy?: string;
}
export interface FormDefinition {
    formName: string;
    fields: Array<FormField>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ImportStatus {
    errors: Array<{
        row: bigint;
        message: string;
    }>;
    totalRows: bigint;
    timestamp: Time;
    successfulRows: bigint;
    failedRows: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Date_Text_Number {
    Date_ = "Date",
    Text = "Text",
    Number = "Number"
}
export enum Variant_Date_Textarea_Text_Checkbox_Number_Dropdown {
    Date_ = "Date",
    Textarea = "Textarea",
    Text = "Text",
    Checkbox = "Checkbox",
    Number = "Number",
    Dropdown = "Dropdown"
}
export enum Variant_Sum_Average_Count {
    Sum = "Sum",
    Average = "Average",
    Count = "Count"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDropdownOption(dropdownName: string, option: DropdownOption): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEntity(formName: string, data: Array<[string, string]>): Promise<string>;
    createForm(form: FormDefinition): Promise<void>;
    createReport(report: ReportDefinition): Promise<void>;
    getAllForms(): Promise<Array<FormDefinition>>;
    getAllReports(): Promise<Array<ReportDefinition>>;
    getCallerUserRole(): Promise<UserRole>;
    getDropdownOptions(dropdownName: string): Promise<Array<DropdownOption>>;
    getEntities(formName: string): Promise<Array<EntityRecord>>;
    getEntity(formName: string, id: string): Promise<EntityRecord | null>;
    getForm(formName: string): Promise<FormDefinition | null>;
    getImportStatus(formName: string): Promise<ImportStatus | null>;
    getReport(reportName: string): Promise<ReportDefinition | null>;
    isCallerAdmin(): Promise<boolean>;
    updateImportStatus(formName: string, status: ImportStatus): Promise<void>;
}
import type { DropdownOption as _DropdownOption, EntityRecord as _EntityRecord, FormDefinition as _FormDefinition, FormField as _FormField, ImportStatus as _ImportStatus, ReportDefinition as _ReportDefinition, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDropdownOption(arg0: string, arg1: DropdownOption): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDropdownOption(arg0, to_candid_DropdownOption_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDropdownOption(arg0, to_candid_DropdownOption_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEntity(arg0: string, arg1: Array<[string, string]>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEntity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEntity(arg0, arg1);
            return result;
        }
    }
    async createForm(arg0: FormDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createForm(to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForm(to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReport(arg0: ReportDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(to_candid_ReportDefinition_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(to_candid_ReportDefinition_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllForms(): Promise<Array<FormDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllForms();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllForms();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<ReportDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDropdownOptions(arg0: string): Promise<Array<DropdownOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDropdownOptions(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDropdownOptions(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntities(arg0: string): Promise<Array<EntityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntities(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntities(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntity(arg0: string, arg1: string): Promise<EntityRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntity(arg0, arg1);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntity(arg0, arg1);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForm(arg0: string): Promise<FormDefinition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForm(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForm(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImportStatus(arg0: string): Promise<ImportStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportStatus(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportStatus(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<ReportDefinition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateImportStatus(arg0: string, arg1: ImportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImportStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImportStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DropdownOption_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DropdownOption): DropdownOption {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_EntityRecord_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityRecord): EntityRecord {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_FormDefinition_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormDefinition): FormDefinition {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_FormField_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormField): FormField {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ReportDefinition_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportDefinition): ReportDefinition {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntityRecord]): EntityRecord | null {
    return value.length === 0 ? null : from_candid_EntityRecord_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FormDefinition]): FormDefinition | null {
    return value.length === 0 ? null : from_candid_FormDefinition_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImportStatus]): ImportStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportDefinition]): ReportDefinition | null {
    return value.length === 0 ? null : from_candid_ReportDefinition_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    formName: string;
    fields: Array<_FormField>;
}): {
    formName: string;
    fields: Array<FormField>;
} {
    return {
        formName: value.formName,
        fields: from_candid_vec_n29(_uploadFile, _downloadFile, value.fields)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: bigint;
    displayLabel: string;
    required: boolean;
    options: [] | [Array<string>];
    fieldName: string;
    fieldType: {
        Date: null;
    } | {
        Textarea: null;
    } | {
        Text: null;
    } | {
        Checkbox: null;
    } | {
        Number: null;
    } | {
        Dropdown: null;
    };
}): {
    order: bigint;
    displayLabel: string;
    required: boolean;
    options?: Array<string>;
    fieldName: string;
    fieldType: Variant_Date_Textarea_Text_Checkbox_Number_Dropdown;
} {
    return {
        order: value.order,
        displayLabel: value.displayLabel,
        required: value.required,
        options: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.options)),
        fieldName: value.fieldName,
        fieldType: from_candid_variant_n33(_uploadFile, _downloadFile, value.fieldType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filters: Array<{
        filterType: {
            Date: null;
        } | {
            Text: null;
        } | {
            Number: null;
        };
        fieldName: string;
    }>;
    metrics: Array<{
        metricType: {
            Sum: null;
        } | {
            Average: null;
        } | {
            Count: null;
        };
        fieldName: string;
    }>;
    reportName: string;
    groupBy: [] | [string];
}): {
    filters: Array<{
        filterType: Variant_Date_Text_Number;
        fieldName: string;
    }>;
    metrics: Array<{
        metricType: Variant_Sum_Average_Count;
        fieldName: string;
    }>;
    reportName: string;
    groupBy?: string;
} {
    return {
        filters: from_candid_vec_n37(_uploadFile, _downloadFile, value.filters),
        metrics: from_candid_vec_n40(_uploadFile, _downloadFile, value.metrics),
        reportName: value.reportName,
        groupBy: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.groupBy))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filterType: {
        Date: null;
    } | {
        Text: null;
    } | {
        Number: null;
    };
    fieldName: string;
}): {
    filterType: Variant_Date_Text_Number;
    fieldName: string;
} {
    return {
        filterType: from_candid_variant_n39(_uploadFile, _downloadFile, value.filterType),
        fieldName: value.fieldName
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metricType: {
        Sum: null;
    } | {
        Average: null;
    } | {
        Count: null;
    };
    fieldName: string;
}): {
    metricType: Variant_Sum_Average_Count;
    fieldName: string;
} {
    return {
        metricType: from_candid_variant_n42(_uploadFile, _downloadFile, value.metricType),
        fieldName: value.fieldName
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    value: string;
    parent: [] | [string];
}): {
    displayName: string;
    value: string;
    parent?: string;
} {
    return {
        displayName: value.displayName,
        value: value.value,
        parent: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.parent))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    data: Array<[string, string]>;
    createdAt: _Time;
    formName: string;
    updatedAt: [] | [_Time];
}): {
    id: string;
    data: Array<[string, string]>;
    createdAt: Time;
    formName: string;
    updatedAt?: Time;
} {
    return {
        id: value.id,
        data: value.data,
        createdAt: value.createdAt,
        formName: value.formName,
        updatedAt: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.updatedAt))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Date: null;
} | {
    Textarea: null;
} | {
    Text: null;
} | {
    Checkbox: null;
} | {
    Number: null;
} | {
    Dropdown: null;
}): Variant_Date_Textarea_Text_Checkbox_Number_Dropdown {
    return "Date" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Date : "Textarea" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Textarea : "Text" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Text : "Checkbox" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Checkbox : "Number" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Number : "Dropdown" in value ? Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Dropdown : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Date: null;
} | {
    Text: null;
} | {
    Number: null;
}): Variant_Date_Text_Number {
    return "Date" in value ? Variant_Date_Text_Number.Date : "Text" in value ? Variant_Date_Text_Number.Text : "Number" in value ? Variant_Date_Text_Number.Number : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sum: null;
} | {
    Average: null;
} | {
    Count: null;
}): Variant_Sum_Average_Count {
    return "Sum" in value ? Variant_Sum_Average_Count.Sum : "Average" in value ? Variant_Sum_Average_Count.Average : "Count" in value ? Variant_Sum_Average_Count.Count : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormDefinition>): Array<FormDefinition> {
    return value.map((x)=>from_candid_FormDefinition_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormField>): Array<FormField> {
    return value.map((x)=>from_candid_FormField_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportDefinition>): Array<ReportDefinition> {
    return value.map((x)=>from_candid_ReportDefinition_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    filterType: {
        Date: null;
    } | {
        Text: null;
    } | {
        Number: null;
    };
    fieldName: string;
}>): Array<{
    filterType: Variant_Date_Text_Number;
    fieldName: string;
}> {
    return value.map((x)=>from_candid_record_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    metricType: {
        Sum: null;
    } | {
        Average: null;
    } | {
        Count: null;
    };
    fieldName: string;
}>): Array<{
    metricType: Variant_Sum_Average_Count;
    fieldName: string;
}> {
    return value.map((x)=>from_candid_record_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DropdownOption>): Array<DropdownOption> {
    return value.map((x)=>from_candid_DropdownOption_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EntityRecord>): Array<EntityRecord> {
    return value.map((x)=>from_candid_EntityRecord_n50(_uploadFile, _downloadFile, x));
}
function to_candid_DropdownOption_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DropdownOption): _DropdownOption {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_FormDefinition_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormDefinition): _FormDefinition {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FormField_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormField): _FormField {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ReportDefinition_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportDefinition): _ReportDefinition {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    formName: string;
    fields: Array<FormField>;
}): {
    formName: string;
    fields: Array<_FormField>;
} {
    return {
        formName: value.formName,
        fields: to_candid_vec_n14(_uploadFile, _downloadFile, value.fields)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: bigint;
    displayLabel: string;
    required: boolean;
    options?: Array<string>;
    fieldName: string;
    fieldType: Variant_Date_Textarea_Text_Checkbox_Number_Dropdown;
}): {
    order: bigint;
    displayLabel: string;
    required: boolean;
    options: [] | [Array<string>];
    fieldName: string;
    fieldType: {
        Date: null;
    } | {
        Textarea: null;
    } | {
        Text: null;
    } | {
        Checkbox: null;
    } | {
        Number: null;
    } | {
        Dropdown: null;
    };
} {
    return {
        order: value.order,
        displayLabel: value.displayLabel,
        required: value.required,
        options: value.options ? candid_some(value.options) : candid_none(),
        fieldName: value.fieldName,
        fieldType: to_candid_variant_n17(_uploadFile, _downloadFile, value.fieldType)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filters: Array<{
        filterType: Variant_Date_Text_Number;
        fieldName: string;
    }>;
    metrics: Array<{
        metricType: Variant_Sum_Average_Count;
        fieldName: string;
    }>;
    reportName: string;
    groupBy?: string;
}): {
    filters: Array<{
        filterType: {
            Date: null;
        } | {
            Text: null;
        } | {
            Number: null;
        };
        fieldName: string;
    }>;
    metrics: Array<{
        metricType: {
            Sum: null;
        } | {
            Average: null;
        } | {
            Count: null;
        };
        fieldName: string;
    }>;
    reportName: string;
    groupBy: [] | [string];
} {
    return {
        filters: to_candid_vec_n20(_uploadFile, _downloadFile, value.filters),
        metrics: to_candid_vec_n23(_uploadFile, _downloadFile, value.metrics),
        reportName: value.reportName,
        groupBy: value.groupBy ? candid_some(value.groupBy) : candid_none()
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filterType: Variant_Date_Text_Number;
    fieldName: string;
}): {
    filterType: {
        Date: null;
    } | {
        Text: null;
    } | {
        Number: null;
    };
    fieldName: string;
} {
    return {
        filterType: to_candid_variant_n22(_uploadFile, _downloadFile, value.filterType),
        fieldName: value.fieldName
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metricType: Variant_Sum_Average_Count;
    fieldName: string;
}): {
    metricType: {
        Sum: null;
    } | {
        Average: null;
    } | {
        Count: null;
    };
    fieldName: string;
} {
    return {
        metricType: to_candid_variant_n25(_uploadFile, _downloadFile, value.metricType),
        fieldName: value.fieldName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    value: string;
    parent?: string;
}): {
    displayName: string;
    value: string;
    parent: [] | [string];
} {
    return {
        displayName: value.displayName,
        value: value.value,
        parent: value.parent ? candid_some(value.parent) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Date_Textarea_Text_Checkbox_Number_Dropdown): {
    Date: null;
} | {
    Textarea: null;
} | {
    Text: null;
} | {
    Checkbox: null;
} | {
    Number: null;
} | {
    Dropdown: null;
} {
    return value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Date ? {
        Date_: null
    } : value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Textarea ? {
        Textarea: null
    } : value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Text ? {
        Text: null
    } : value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Checkbox ? {
        Checkbox: null
    } : value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Number ? {
        Number: null
    } : value == Variant_Date_Textarea_Text_Checkbox_Number_Dropdown.Dropdown ? {
        Dropdown: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Date_Text_Number): {
    Date: null;
} | {
    Text: null;
} | {
    Number: null;
} {
    return value == Variant_Date_Text_Number.Date ? {
        Date_: null
    } : value == Variant_Date_Text_Number.Text ? {
        Text: null
    } : value == Variant_Date_Text_Number.Number ? {
        Number: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Sum_Average_Count): {
    Sum: null;
} | {
    Average: null;
} | {
    Count: null;
} {
    return value == Variant_Sum_Average_Count.Sum ? {
        Sum: null
    } : value == Variant_Sum_Average_Count.Average ? {
        Average: null
    } : value == Variant_Sum_Average_Count.Count ? {
        Count: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FormField>): Array<_FormField> {
    return value.map((x)=>to_candid_FormField_n15(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    filterType: Variant_Date_Text_Number;
    fieldName: string;
}>): Array<{
    filterType: {
        Date: null;
    } | {
        Text: null;
    } | {
        Number: null;
    };
    fieldName: string;
}> {
    return value.map((x)=>to_candid_record_n21(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    metricType: Variant_Sum_Average_Count;
    fieldName: string;
}>): Array<{
    metricType: {
        Sum: null;
    } | {
        Average: null;
    } | {
        Count: null;
    };
    fieldName: string;
}> {
    return value.map((x)=>to_candid_record_n24(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
